-- Migration: External (non-app) booking conversations
--
-- Adds support for booking requests submitted from a shared vendor link by
-- people who do not yet have a Plano account (web page or App Clip).
--
-- The submission becomes a normal conversation + booking_request that the
-- vendor sees in their inbox. The host side is represented by external_email
-- + external_first_name + external_last_name on the conversation, and host_id
-- is left NULL until the external user installs the app and claims it.
--
-- State transitions (accept/decline/message) generated by the vendor enqueue
-- rows into external_email_jobs; an edge function drains the queue and sends
-- transactional emails containing a claim deep link.

begin;

-- ---------------------------------------------------------------------------
-- 1. conversations: allow external-host rows
-- ---------------------------------------------------------------------------

alter table public.conversations
  alter column host_id drop not null;

alter table public.conversations
  add column if not exists external_email text,
  add column if not exists external_first_name text,
  add column if not exists external_last_name text,
  add column if not exists external_source text;

alter table public.conversations
  drop constraint if exists conversations_external_source_check;

alter table public.conversations
  add constraint conversations_external_source_check
  check (external_source is null or external_source in ('app_clip', 'web'));

alter table public.conversations
  drop constraint if exists conversations_host_or_external_check;

alter table public.conversations
  add constraint conversations_host_or_external_check
  check (host_id is not null or external_email is not null);

create index if not exists conversations_external_email_idx
  on public.conversations (lower(external_email))
  where external_email is not null;

-- ---------------------------------------------------------------------------
-- 2. bookings: allow null host_id until claim happens
-- ---------------------------------------------------------------------------

alter table public.bookings
  alter column host_id drop not null;

-- ---------------------------------------------------------------------------
-- 3. external_booking_invites: claim tokens mailed to external users
-- ---------------------------------------------------------------------------

create table if not exists public.external_booking_invites (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  email text not null,
  token text unique not null,
  expires_at timestamptz not null,
  claimed_by uuid references public.users (id) on delete set null,
  claimed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists external_booking_invites_email_idx
  on public.external_booking_invites (lower(email));

create index if not exists external_booking_invites_conversation_idx
  on public.external_booking_invites (conversation_id);

alter table public.external_booking_invites enable row level security;

-- No public policies. Service role only (bypasses RLS). Claim & list flow
-- through security-definer RPCs below.

-- ---------------------------------------------------------------------------
-- 4. external_email_jobs: transactional email queue for guest hosts
-- ---------------------------------------------------------------------------

create table if not exists public.external_email_jobs (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations (id) on delete cascade,
  kind text not null check (kind in (
    'request_received',
    'vendor_accepted',
    'vendor_declined',
    'vendor_quoted',
    'vendor_messaged',
    'payment_requested',
    'cancelled'
  )),
  payload jsonb not null default '{}'::jsonb,
  attempts int not null default 0,
  max_attempts int not null default 5,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists external_email_jobs_pending_idx
  on public.external_email_jobs (created_at)
  where sent_at is null;

alter table public.external_email_jobs enable row level security;
-- service role only.

-- ---------------------------------------------------------------------------
-- 5. submit_external_booking_request
--    Creates a conversation + booking_request + invite token in one shot.
--    Called by the public submit-external-booking edge function.
-- ---------------------------------------------------------------------------

create or replace function public.submit_external_booking_request(
  p_vendor_id uuid,
  p_first_name text,
  p_last_name text,
  p_email text,
  p_event_date date,
  p_guest_count int default null,
  p_note text default '',
  p_intake_answers jsonb default '[]'::jsonb,
  p_source text default 'web'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_vendor public.vendor_profiles%rowtype;
  v_conversation_id uuid;
  v_request_id uuid;
  v_token text;
  v_host_display text;
  v_event_date_label text;
  v_event_context_line text;
  v_email text := lower(trim(p_email));
  v_first text := trim(p_first_name);
  v_last text := trim(p_last_name);
  v_guest_label text;
  v_now timestamptz := timezone('utc', now());
begin
  if v_email is null or v_email = '' or v_email not like '%@%' then
    raise exception 'A valid email address is required.';
  end if;

  if v_first is null or v_first = '' or v_last is null or v_last = '' then
    raise exception 'First and last name are required.';
  end if;

  if p_event_date is null then
    raise exception 'Event date is required.';
  end if;

  select *
  into v_vendor
  from public.vendor_profiles
  where user_id = p_vendor_id;

  if not found then
    raise exception 'Vendor not found.';
  end if;

  v_host_display := v_first || ' ' || v_last;
  v_event_date_label := to_char(p_event_date, 'Mon DD, YYYY');
  v_event_context_line := 'Booking request for ' || v_event_date_label;
  if p_guest_count is not null and p_guest_count > 0 then
    v_guest_label := p_guest_count::text || ' guests';
  else
    v_guest_label := '';
  end if;

  -- Conversation row. host_id stays NULL until the external user claims.
  insert into public.conversations (
    event_id,
    vendor_id,
    host_id,
    host_display_name,
    vendor_display_name,
    vendor_category,
    event_title,
    event_date_label,
    event_context_line,
    stage,
    last_activity_at,
    created_at,
    updated_at,
    external_email,
    external_first_name,
    external_last_name,
    external_source
  )
  values (
    null,
    p_vendor_id,
    null,
    v_host_display,
    v_vendor.business_name,
    coalesce(v_vendor.category, 'General'),
    'Booking request',
    v_event_date_label,
    v_event_context_line,
    'requested',
    v_now,
    v_now,
    v_now,
    v_email,
    v_first,
    v_last,
    coalesce(p_source, 'web')
  )
  returning id into v_conversation_id;

  -- Booking request. Uses the same shape the in-app flow produces so the
  -- vendor inbox renders it identically.
  insert into public.booking_requests (
    conversation_id,
    title,
    budget_label,
    response_window_label,
    requested_services,
    note,
    guest_count_label,
    event_date,
    intake_answers
  )
  values (
    v_conversation_id,
    'External booking request',
    '',
    '',
    '{}'::text[],
    coalesce(p_note, ''),
    v_guest_label,
    p_event_date,
    coalesce(p_intake_answers, '[]'::jsonb)
  )
  returning id into v_request_id;

  -- System message shown to the vendor in the thread.
  insert into public.messages (
    conversation_id,
    sender_role,
    body,
    kind,
    created_at
  )
  values (
    v_conversation_id,
    'system',
    v_host_display || ' requested ' || v_event_date_label || ' via your booking link',
    'system',
    v_now
  );

  -- Mint a claim token, valid for 30 days.
  v_token := encode(gen_random_bytes(24), 'base64');
  v_token := replace(replace(replace(v_token, '+', '-'), '/', '_'), '=', '');

  insert into public.external_booking_invites (
    conversation_id,
    email,
    token,
    expires_at
  )
  values (
    v_conversation_id,
    v_email,
    v_token,
    v_now + interval '30 days'
  );

  -- Enqueue the request-received confirmation email.
  insert into public.external_email_jobs (conversation_id, kind, payload)
  values (
    v_conversation_id,
    'request_received',
    jsonb_build_object(
      'vendor_name', v_vendor.business_name,
      'event_date_label', v_event_date_label,
      'first_name', v_first
    )
  );

  return jsonb_build_object(
    'conversation_id', v_conversation_id,
    'booking_request_id', v_request_id,
    'invite_token', v_token
  );
end;
$$;

revoke all on function public.submit_external_booking_request(
  uuid, text, text, text, date, int, text, jsonb, text
) from public, anon, authenticated;
grant execute on function public.submit_external_booking_request(
  uuid, text, text, text, date, int, text, jsonb, text
) to service_role;

-- ---------------------------------------------------------------------------
-- 6. claim_external_booking
--    Links an authenticated user to an external-host conversation by token,
--    after verifying the user's email matches the invite.
-- ---------------------------------------------------------------------------

create or replace function public.claim_external_booking(
  p_user_id uuid,
  p_user_email text,
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.external_booking_invites%rowtype;
  v_conversation public.conversations%rowtype;
  v_user public.users%rowtype;
  v_display_name text;
  v_now timestamptz := timezone('utc', now());
  v_user_email text := lower(trim(p_user_email));
begin
  if p_token is null or p_token = '' then
    raise exception 'Invite token is required.';
  end if;

  select *
  into v_invite
  from public.external_booking_invites
  where token = p_token;

  if not found then
    raise exception 'Invite not found.';
  end if;

  if v_invite.expires_at < v_now then
    raise exception 'Invite has expired.';
  end if;

  -- Idempotent: already claimed by this user → no-op.
  if v_invite.claimed_by is not null then
    if v_invite.claimed_by = p_user_id then
      return jsonb_build_object('conversation_id', v_invite.conversation_id);
    end if;
    raise exception 'Invite has already been claimed.';
  end if;

  if lower(v_invite.email) <> v_user_email then
    raise exception 'This invite was sent to a different email address.';
  end if;

  select *
  into v_conversation
  from public.conversations
  where id = v_invite.conversation_id
  for update;

  if not found then
    raise exception 'Conversation not found.';
  end if;

  select *
  into v_user
  from public.users
  where id = p_user_id;

  if found then
    v_display_name := coalesce(nullif(trim(v_user.display_name), ''), v_conversation.host_display_name);
  else
    v_display_name := v_conversation.host_display_name;
  end if;

  update public.conversations
  set host_id = p_user_id,
      host_display_name = v_display_name,
      external_email = null,
      external_first_name = null,
      external_last_name = null,
      last_activity_at = greatest(last_activity_at, v_now),
      updated_at = v_now
  where id = v_invite.conversation_id;

  -- Pick up any bookings row created during an accept that happened before the claim.
  update public.bookings
  set host_id = p_user_id,
      updated_at = v_now
  where conversation_id = v_invite.conversation_id
    and host_id is null;

  update public.external_booking_invites
  set claimed_by = p_user_id,
      claimed_at = v_now
  where id = v_invite.id;

  return jsonb_build_object('conversation_id', v_invite.conversation_id);
end;
$$;

revoke all on function public.claim_external_booking(uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.claim_external_booking(uuid, text, text) to service_role;

-- ---------------------------------------------------------------------------
-- 7. list_claimable_invites_for_email
--    Called after a user signs in to sweep up any pending invites whose email
--    matches theirs even if they never tapped a link.
-- ---------------------------------------------------------------------------

create or replace function public.list_claimable_invites_for_email(
  p_email text
)
returns table (
  token text,
  conversation_id uuid,
  expires_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select token, conversation_id, expires_at
  from public.external_booking_invites
  where lower(email) = lower(trim(p_email))
    and claimed_at is null
    and expires_at > timezone('utc', now());
$$;

revoke all on function public.list_claimable_invites_for_email(text)
  from public, anon, authenticated;
grant execute on function public.list_claimable_invites_for_email(text) to service_role;

-- ---------------------------------------------------------------------------
-- 8. Triggers that enqueue guest-side emails on state transitions.
--    Keeping this in Postgres means no edits to existing edge functions.
-- ---------------------------------------------------------------------------

create or replace function public.enqueue_external_email_for_booking_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conversation public.conversations%rowtype;
  v_vendor_name text;
  v_kind text;
begin
  select *
  into v_conversation
  from public.conversations
  where id = new.conversation_id;

  if not found or v_conversation.external_email is null then
    return new;
  end if;

  v_vendor_name := coalesce(v_conversation.vendor_display_name, 'Your vendor');

  v_kind := case new.to_stage
    when 'accepted' then 'vendor_accepted'
    when 'quoted' then 'vendor_quoted'
    when 'declined' then 'vendor_declined'
    when 'cancelled' then 'cancelled'
    when 'deposit_pending' then 'payment_requested'
    else null
  end;

  if v_kind is null then
    return new;
  end if;

  insert into public.external_email_jobs (conversation_id, kind, payload)
  values (
    new.conversation_id,
    v_kind,
    jsonb_build_object(
      'vendor_name', v_vendor_name,
      'event_date_label', v_conversation.event_date_label,
      'to_stage', new.to_stage,
      'from_stage', new.from_stage
    )
  );

  return new;
end;
$$;

drop trigger if exists enqueue_external_email_on_booking_event on public.booking_events;
create trigger enqueue_external_email_on_booking_event
after insert on public.booking_events
for each row
execute function public.enqueue_external_email_for_booking_event();

-- Vendor messages to external hosts: throttle to at most one email per 30min
-- per conversation, so rapid follow-ups don't spam the external inbox.

create or replace function public.enqueue_external_email_for_vendor_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conversation public.conversations%rowtype;
  v_recent_count int;
begin
  if new.sender_role <> 'vendor' or new.kind = 'system' then
    return new;
  end if;

  select *
  into v_conversation
  from public.conversations
  where id = new.conversation_id;

  if not found or v_conversation.external_email is null then
    return new;
  end if;

  -- Throttle: suppress if a vendor_messaged job was enqueued in the last 30 minutes.
  select count(*)
  into v_recent_count
  from public.external_email_jobs
  where conversation_id = new.conversation_id
    and kind = 'vendor_messaged'
    and created_at > timezone('utc', now()) - interval '30 minutes';

  if v_recent_count > 0 then
    return new;
  end if;

  insert into public.external_email_jobs (conversation_id, kind, payload)
  values (
    new.conversation_id,
    'vendor_messaged',
    jsonb_build_object(
      'vendor_name', coalesce(v_conversation.vendor_display_name, 'Your vendor'),
      'event_date_label', v_conversation.event_date_label
    )
  );

  return new;
end;
$$;

drop trigger if exists enqueue_external_email_on_vendor_message on public.messages;
create trigger enqueue_external_email_on_vendor_message
after insert on public.messages
for each row
execute function public.enqueue_external_email_for_vendor_message();

commit;
